goroskop/urls.py
from django.urls import path
from . import views

app_name = 'goroskop'

urlpatterns = [
    path('', views.page, name='page'),
    path('item/<slug:item_slug>/', views.show_post, name='item'),
    path('category/<slug:cat_id>/', views.show_category, name='category')
]

lavka/urls.py
from django.urls import path
from . import views

app_name = 'lavka'

urlpatterns = [
    path('', views.about, name='about'),
    path('post/<slug:post_slug>/', views.show_post, name='post'),
    path('category/<slug:cat_id>/', views.show_category, name='category'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lavka.urls', namespace='lavka')),
    path('index/', include('sonnik.urls', namespace='sonnik')),
    path('page/', include('goroskop.urls', namespace='goroskop')),
    path('contact/', include('taro.urls', namespace='taro')),
]

sonnik/urls.py
from django.urls import path
from . import views

app_name = 'sonnik'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<slug:post_slug>/', views.show_post, name='post'),
    path('category/<slug:cat_id>/', views.show_category, name='category'),
]

taro/urls.py
from django.urls import path
from . import views

app_name = 'taro'

urlpatterns = [
    path('', views.contact, name='contact'),
    path('stap/<slug:stap_slug>/', views.show_post, name='stap'),
    path('category/<slug:cat_id>/', views.show_category, name='category')
]

mysite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/mainbar.css' %}">
    <link rel="stylesheet" href="{% static 'images/' %}">
</head>

<body>
    <header>
        <div class="topnav">
            <a href="{% url 'lavka:about' %}">Главная</a>
            <a href="{% url 'sonnik:index' %}">Сонник</a>
            <a href="{% url 'goroskop:page' %}">Гороскоп</a>
            <a href="{% url 'taro:contact' %}">Таро</a>
        </div>
    </header>   

    <div class="main-bar">
        <div class="left-bar">
            <h3>
            {% for m in menu %}    
            {% if cat_selected == 0 %}
                <div class="leftbar">Все категории</div>
            {% else %}
                <a href="{% url m.url_name %}">Все категории</a>
            {% endif %}
            {% endfor %}

            {% for cat in cats %}
            {% if cat.pk == cat_selected %}
                <li class="selected">{{ cat.name }}</li>
            {% else %}
                <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
            {% endif %}    
            {% endfor %}
            </h3>
        </div>

        <div class="conteiner">
            {% block content %}
            {% endblock %}    
        </div>

        <div class="rite-bar">
            {% comment %} {% include "about" %}                       {% endcomment %}
        </div>
    </div>

</body>

</html>